#!/bin/bash
#PBS -V
#PBS -N split_intervals
#PBS -l nodes=1:ppn=1,mem=4gb,walltime=500:00:00
#PBS -q batch
#PBS -o /usr/scratch2/userdata2/mtofflemire/projects/picoides_genotyping/out/split_intervals.log
#PBS -j oe

set -euo pipefail
cd "$PBS_O_WORKDIR"

# env (needed so gatk/samtools are available)
source ~/miniconda3/etc/profile.d/conda.sh
conda activate genomics

# --- Paths ---
PRJ=/usr/scratch2/userdata2/mtofflemire/projects/picoides_genotyping
REF=/usr/scratch2/userdata2/mtofflemire/references/ncbi_dataset/data/GCF_014839835.1/GCF_014839835.1_bDryPub1.pri_genomic.fna
SHARDS_DIR=$PRJ/SNP_calling/joint_gatk4_gdb/shards
SPLITS=48

mkdir -p "$SHARDS_DIR"

# ensure required reference index/dict exist (quiet, only if missing)
[ -f "${REF}.fai" ] || samtools faidx "$REF"
DICT="${REF%.*}.dict"
[ -f "$DICT" ] || gatk CreateSequenceDictionary -R "$REF" -O "$DICT"

# Generate 48 roughly equal genomic intervals
gatk SplitIntervals -R "$REF" --scatter-count "$SPLITS" -O "$SHARDS_DIR"

echo "Shards created in: $SHARDS_DIR"

