# 07_gather_raw_picoides.pbs
#!/bin/bash
#PBS -V
#PBS -N gather_raw_picoides
#PBS -l nodes=1:ppn=4,mem=64gb,walltime=500:00:00
#PBS -q batch
#PBS -o /usr/scratch2/userdata2/mtofflemire/projects/leuconotopicus/reseq_WD/logs/gather_raw_picoides.log
#PBS -j oe

set -euo pipefail
cd "$PBS_O_WORKDIR"

source ~/miniconda3/etc/profile.d/conda.sh
conda activate genomics

PRJ=/usr/scratch2/userdata2/mtofflemire/projects/leuconotopicus
REF=$PRJ/ref_genome/GCF_014839835.1_bDryPub1.pri_genomic.fna
DICT=${REF%.fna}.dict

IN_DIR=$PRJ/reseq_WD/03_vcf
OUT_DIR=$PRJ/reseq_WD/04_vcf

mkdir -p "$OUT_DIR"
cd "$IN_DIR"

# Gather shards -> single cohort all-sites VCF
gatk GatherVcfs \
  $(printf -- '-I cohort.allsites.%03d.vcf.gz ' $(seq 0 47)) \
  -O "$OUT_DIR/leuconotopicus.allsites.merged.vcf.gz"

# Sort merged VCF
gatk SortVcf \
  -I "$OUT_DIR/leuconotopicus.allsites.merged.vcf.gz" \
  -O "$OUT_DIR/leuconotopicus.allsites.merged.sorted.vcf.gz" \
  --SEQUENCE_DICTIONARY "$DICT"

# Index the sorted VCF
gatk IndexFeatureFile -I "$OUT_DIR/leuconotopicus.allsites.merged.sorted.vcf.gz"
