#!/bin/bash
#PBS -V
#PBS -N subsample_allsites_100k
#PBS -l nodes=1:ppn=4,mem=64gb,walltime=500:00:00
#PBS -q batch
#PBS -o /usr/scratch2/userdata2/mtofflemire/projects/leuconotopicus/reseq_WD/logs/prune_allsites_vcf.log
#PBS -j oe

set -euo pipefail

WORKDIR="/usr/scratch2/userdata2/mtofflemire/projects/leuconotopicus/reseq_WD/04_vcf"
cd "$WORKDIR"

source ~/miniconda3/etc/profile.d/conda.sh
conda activate vcflib_env

BCFTOOLS="$HOME/.conda/envs/genomics/bin/bcftools"
INPUT="leuconotopicus.allsites.merged.sorted.vcf.gz"
OUTPUT="leuconotopicus.allsites.pruned.vcf.gz"
RATE="0.00008418"

"$BCFTOOLS" view "$INPUT" \
  | vcfrandomsample -r "$RATE" \
  | bgzip -c > "$OUTPUT"

tabix -p vcf "$OUTPUT"
