#!/bin/bash
#PBS -V
#PBS -N plot_pca
#PBS -l nodes=1:ppn=1,mem=4gb,walltime=00:10:00
#PBS -q batch
#PBS -o /usr/scratch2/userdata2/mtofflemire/projects/picoides_genotyping/out/plot_pca.log
#PBS -j oe

set -euo pipefail
cd "$PBS_O_WORKDIR"

# Use the env that has R (your 'genomics' env shows r-base in its package list)
source ~/miniconda3/etc/profile.d/conda.sh
conda activate genomics

# sanity check (goes to log)
which Rscript || true
Rscript --version || true

# run the script
Rscript 12_plot_pca.R

