#!/bin/sh
#PBS -V
#PBS -l nodes=1:ppn=18  # Request 12 cores
#PBS -l mem=128gb        # Allocate 64GB of memory
#PBS -l walltime=72:00:00  # Set max runtime (72 hours)
#PBS -N iqtree_analysis  # Job name
#PBS -j oe               # Merge stdout and stderr into a single file
#PBS -M mtofflemire@sdsu.edu   # Email notifications (if needed)
#PBS -q batch            # Submit to the batch queue
#PBS -o /usr/scratch2/userdata2/mtofflemire/projects/chamaea/Chamaea.final.pruned_population_only.counts_3.log  # Output log

# Change to the working directory
cd $PBS_O_WORKDIR

# Run IQ-TREE with the correct paths
/usr/scratch2/userdata2/mtofflemire/projects/chamaea/systems/iqtree-2.2.2.7-Linux/bin/iqtree2 \
  -s /usr/scratch2/userdata2/mtofflemire/projects/chamaea/Chamaea.pomo_no_outgroup.counts \
  -m TESTONLY \
  -nt 18 \
  -redo
