#!/bin/bash
#PBS -V
#PBS -l nodes=1:ppn=20
#PBS -l mem=128gb
#PBS -l walltime=48:00:00
#PBS -N call_variants_outgroup_gatk
#PBS -j oe
#PBS -M mtofflemire@sdsu.edu
#PBS -o /usr/scratch2/userdata2/mtofflemire/projects/chamaea/out/call_variants_gatk_updated.log
#PBS -q batch

# Change to the working directory
cd $PBS_O_WORKDIR

# Set output directory
OUTDIR="/usr/scratch2/userdata2/mtofflemire/projects/chamaea/out"

# Ensure output directory exists
mkdir -p $OUTDIR

# Activate your Conda environment with GATK and Samtools
source ~/miniconda3/etc/profile.d/conda.sh
conda activate outgroup_align  # Ensure samtools is installed here

# Run GATK HaplotypeCaller
echo "Running GATK HaplotypeCaller..."
gatk HaplotypeCaller \
    -R /home/mtofflemire/references/GCA_029207755.1/GCA_029207755.1_bChaFas1.0.hap1_genomic.fna \
    -I /usr/scratch2/userdata2/mtofflemire/projects/chamaea/out/SRR8271220.filtered_rg.bam \
    -O $OUTDIR/outgroup_variants_gatk.vcf.gz 	\
    --native-pair-hmm-threads 20

# Index the VCF file
echo "Indexing VCF file..."
gatk IndexFeatureFile -I $OUTDIR/outgroup_variants_gatk.vcf.gz

echo "✅ GATK Variant Calling and Indexing Complete!"
