# 10_filter_vcf_2.pbs
#!/bin/bash
#PBS -V
#PBS -N maf05_mm75_thin1kb
#PBS -l nodes=1:ppn=20,mem=64gb,walltime=04:00:00
#PBS -q batch
#PBS -o /usr/scratch2/userdata2/mtofflemire/projects/picoides_genotyping/out/vcf_pruned.log
#PBS -j oe

set -euo pipefail
cd "$PBS_O_WORKDIR"

source ~/miniconda3/etc/profile.d/conda.sh
conda activate genomics

OUT2=/usr/scratch2/userdata2/mtofflemire/projects/picoides_genotyping/out2
IN=$OUT2/picoides.snps.filteredQC.vcf.gz
OUT=$OUT2/picoides.snps.pruned.vcf.gz

[ -s "$IN.tbi" ] || tabix -p vcf "$IN"

bcftools +fill-tags "$IN" -Ou -- -t MAF,F_MISSING \
| bcftools view -v snps -m2 -M2 -i 'MAF>=0.01 && F_MISSING<=0.75' --threads 10 -Ou \
| bcftools +prune -n 1 -w 1kb -Oz -o "$OUT"

tabix -f -p vcf "$OUT"
