#!/bin/bash
#PBS -V
#PBS -N extract_variant_sites
#PBS -l nodes=1:ppn=20,mem=128gb,walltime=48:00:00
#PBS -q batch
#PBS -o /usr/scratch2/userdata2/mtofflemire/projects/leuconotopicus/reseq_WD/logs/extract_variant_sites.log
#PBS -j oe

set -euo pipefail
cd "$PBS_O_WORKDIR"

source ~/miniconda3/etc/profile.d/conda.sh
conda activate genomics

PRJ=/usr/scratch2/userdata2/mtofflemire/projects/leuconotopicus
OUT_DIR=$PRJ/reseq_WD/04_vcf

VCF=$OUT_DIR/leuconotopicus.allsites.merged.sorted.vcf.gz
OUTVCF=$OUT_DIR/leuconotopicus.raw.variants.vcf.gz

[ -s "$VCF" ] || { echo "Input VCF not found: $VCF"; exit 1; }
[ -s "$VCF.tbi" ] || tabix -p vcf "$VCF"

bcftools view \
  -e 'ALT="."' \
  -Oz \
  -o "$OUTVCF" \
  "$VCF"

tabix -p vcf "$OUTVCF"

echo "Done: $OUTVCF"

