# 11_convert_plink_like_paper_thin1kb.pbs
#!/bin/bash
#PBS -V
#PBS -N plink_bed_like_paper
#PBS -l nodes=1:ppn=20,mem=32gb,walltime=01:00:00
#PBS -q batch
#PBS -o /usr/scratch2/userdata2/mtofflemire/projects/picoides_genotyping/out/plink_convert.log
#PBS -j oe

set -euo pipefail
cd "$PBS_O_WORKDIR"

# activate plink env (same as your PCA script)
source ~/miniconda3/etc/profile.d/conda.sh
conda activate plink19

OUT2=/usr/scratch2/userdata2/mtofflemire/projects/picoides_genotyping/out2
VCF=$OUT2/picoides.snps.pruned.like_paper.thin1kb.vcf.gz
BED=$OUT2/picoides.like_paper.thin1kb

# VCF -> BED (same flags you used for PCA)
plink \
  --vcf "$VCF" \
  --double-id \
  --allow-extra-chr \
  --set-missing-var-ids @:#:\$1_\$2 \
  --make-bed \
  --threads 20 \
  --out "$BED"

# quick check
ls -lh ${BED}.bed ${BED}.bim ${BED}.fam

