#!/bin/bash
#PBS -V
#PBS -N index_reference_mem2
#PBS -l nodes=node1:ppn=20,mem=128gb,walltime=500:00:00
#PBS -q batch
#PBS -j oe
#PBS -o /usr/scratch2/userdata2/mtofflemire/projects/leuconotopicus/ref_genome/index_reference.log

set -euo pipefail
cd "${PBS_O_WORKDIR:-$PWD}"
source ~/miniconda3/etc/profile.d/conda.sh
conda activate genomics

REF=/usr/scratch2/userdata2/mtofflemire/projects/leuconotopicus/ref_genome/GCF_014839835.1_bDryPub1.pri_genomic.fna

bwa-mem2 index "$REF"
samtools faidx "$REF"
gatk CreateSequenceDictionary -R "$REF" -O "${REF%.*}.dict"
