#!/bin/bash
#PBS -V
#PBS -N index_reference_mem2
#PBS -l nodes=1:ppn=2,mem=8gb,walltime=02:00:00
#PBS -q batch
#PBS -j oe
#PBS -o /usr/scratch2/userdata2/mtofflemire/projects/leuconotopicus/reseq_WD/round_1_preprocessing_wgs/01_index_reference.log

set -euo pipefail
cd "$PBS_O_WORKDIR"
source ~/miniconda3/etc/profile.d/conda.sh; conda activate genomics

bwa-mem2 index /usr/scratch2/userdata2/mtofflemire/projects/leuconotopicus/ref_genome/GCF_014839835.1_bDryPub1.pri_genomic.fna
samtools faidx /usr/scratch2/userdata2/mtofflemire/projects/leuconotopicus/ref_genome/GCF_014839835.1_bDryPub1.pri_genomic.fna
gatk CreateSequenceDictionary -R /usr/scratch2/userdata2/mtofflemire/projects/leuconotopicus/ref_genome/GCF_014839835.1_bDryPub1.pri_genomic.fna -O /usr/scratch2/userdata2/mtofflemire/projects/leuconotopicus/ref_genome/GCF_014839835.1_bDryPub1.pri_genomic.dict
