#!/bin/bash
#PBS -V
#PBS -N align_mem2_only
#PBS -l nodes=1:ppn=20,mem=128gb,walltime=500:00:00
#PBS -q batch
#PBS -j oe
#PBS -o /usr/scratch2/userdata2/mtofflemire/projects/leuconotopicus/reseq_WD/01_bam_files/02_align.log

set -euo pipefail
cd "/usr/scratch2/userdata2/mtofflemire/projects/leuconotopicus/reseq_WD"
source ~/miniconda3/etc/profile.d/conda.sh; 
conda activate genomics

REF="/usr/scratch2/userdata2/mtofflemire/projects/leuconotopicus/ref_genome/GCF_014839835.1_bDryPub1.pri_genomic.fna"

INPUT_DIR="/usr/scratch2/userdata2/mtofflemire/projects/leuconotopicus/reseq_WD/01.1_cleaned"

OUTDIR="/usr/scratch2/userdata2/mtofflemire/projects/leuconotopicus/reseq_WD/01_bam_files"

THREADS=20
mkdir -p "$OUTDIR"

for R1 in "$INPUT_DIR"/*_R1*.fastq.gz; do
  [ -e "$R1" ] || { echo "No R1 files in $INPUT_DIR"; exit 1; }
  R2="${R1/_R1/_R2}"; [ -f "$R2" ] || { echo "Missing mate for $R1"; continue; }
  base="$(basename "$R1")"; BASENAME="${base%%_R1*}"
  SAMPLE="$(echo "$BASENAME" | awk -F'_' '{print $2}')"
  LANE="$(echo "$BASENAME"   | awk -F'_' '{print $3"_"$4}')"
  RGID="${SAMPLE}_${LANE}"; RGSM="$SAMPLE"; RGPU="$LANE"; RGLB="lib1"; RGPL="ILLUMINA"

  bwa-mem2 mem -t $THREADS -R "@RG\tID:${RGID}\tSM:${RGSM}\tLB:${RGLB}\tPL:${RGPL}\tPU:${RGPU}" "$REF" "$R1" "$R2" \
    | samtools sort -@ $((THREADS/2)) -o "${OUTDIR}/${BASENAME}.sorted.bam" -
  samtools index "${OUTDIR}/${BASENAME}.sorted.bam"
  samtools flagstat "${OUTDIR}/${BASENAME}.sorted.bam" > "${OUTDIR}/${BASENAME}.flagstat.txt"
done
