#!/bin/bash
#PBS -V
#PBS -l nodes=1:ppn=10,mem=128gb
#PBS -N 02_markduplicates
#PBS -j oe
#PBS -q batch
#PBS -l walltime=500:00:00
#PBS -o /usr/scratch2/userdata2/mtofflemire/projects/leuconotopicus/reseq_WD/logs/02_markduplicates.log

set -euo pipefail

source ~/miniconda3/etc/profile.d/conda.sh
conda activate genomics

cd $PBS_O_WORKDIR

BAM_DIR="/usr/scratch2/userdata2/mtofflemire/projects/leuconotopicus/reseq_WD/01_bam_files"
FLAGSTAT_DIR="/usr/scratch2/userdata2/mtofflemire/projects/leuconotopicus/reseq_WD/01_bam_files"

for BAM in ${BAM_DIR}/*.sorted.bam; do

    SAMPLE_NAME=$(basename "$BAM" .sorted.bam)

    gatk --java-options "-Xms4g -Xmx16g" MarkDuplicates \
        -I "$BAM" \
        -O "${BAM_DIR}/${SAMPLE_NAME}.dedup.bam" \
        -M "${FLAGSTAT_DIR}/${SAMPLE_NAME}.dup_metrics.txt" \
        --CREATE_INDEX true \
        --VALIDATION_STRINGENCY SILENT

    #samtools index "${BAM_DIR}/${SAMPLE_NAME}.dedup.bam"
    samtools flagstat "${BAM_DIR}/${SAMPLE_NAME}.dedup.bam" > "${FLAGSTAT_DIR}/${SAMPLE_NAME}_dedup.flagstat.txt"

    echo "========== MarkDuplicates finished for $SAMPLE_NAME at $(date) =========="

done

#note: the flagstats made here are the ones usually reported in papers
