#!/bin/bash
#PBS -V
#PBS -N markdups_sambamba
#PBS -l nodes=1:ppn=20,mem=64gb,walltime=12:00:00
#PBS -q batch
#PBS -j oe
#PBS -o /usr/scratch2/userdata2/mtofflemire/projects/leuconotopicus/reseq_WD/01_bam_files/markdups_sambamba.log

set -euo pipefail
cd "$PBS_O_WORKDIR"

source ~/miniconda3/etc/profile.d/conda.sh
conda activate genomics

IN="/usr/scratch2/userdata2/mtofflemire/projects/leuconotopicus/reseq_WD/01_bam_files"

THREADS=20

for BAM in "$IN"/*.sorted.bam; do
  [ -e "$BAM" ] || { exit 1; }
  base="$(basename "$BAM" .sorted.bam)"

  sambamba markdup -t "$THREADS" "$BAM" "$IN/${base}.dedup.bam"
  sambamba index -t "$THREADS" "$IN/${base}.dedup.bam"
  samtools flagstat -@ "$THREADS" "$IN/${base}.dedup.bam" > "$IN/${base}.dedup.flagstat.txt"
done
